server:
  port: 7575

spring:
  datasource:
    url: jdbc:mysql://localhost:5355/DTB?createDatabaseIfNotExist=true
    username: root
    password: password
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    open-in-view: false



